### ISSUE TITLE
Feed tag show issue at Feed Page

### ISSUE THREAD

**Issue by ujjwalnp** [cosmicgz/COREQ#32]
'tag' is not returned as response from backend. So it need to be rendered from front-end.

**Comment by Hunter-420** [comment]
Put tag attribute in user post collection then render it like
tag = {user.tag} --> which is already done
```
        feedPosts.map(user => <PostShow
          name={user.userFullName}
          userName={user.username}
          profileImage={user.profilePic}
          title={user.title}
          description={user.description}
          vote={user.vote}
          tag={user.tag}
          postDate={user.createdAt}
        ></PostShow>)
```

but didn't have tag attribute on post collection

**Comment by ujjwalnp** [comment]
Issue Solved at Backend by changing schema and setting default value
