### ISSUE TITLE
Friend suggestion section is rendering in Improper way

### ISSUE THREAD

**Issue by ujjwalnp** [cosmicgz/COREQ#60]
Follow button should be aligned at the right side correctly!
![image](https://github.com/cosmicgz/COREQ/assets/68050149/5588a27a-a775-47a9-954d-5ddd05300952)

**Comment by Hunter-420** [comment]
issue fixed here is the final result
![image](https://github.com/cosmicgz/COREQ/assets/92971596/529cc930-0a60-4bcf-b08f-b3f5dfe0f082)
![image](https://github.com/cosmicgz/COREQ/assets/92971596/9fc3bbd9-5abe-4be9-ae5b-61a87ce4d2b0)
